// Code generated by MockGen. DO NOT EDIT.
// Source: ../rtmgr_client/handle/handle_client.go

package handle

import (
	"github.com/go-openapi/runtime"
	"github.com/stretchr/testify/mock"
)


type ClientServiceMock struct {
	mock.Mock
}

func (a *ClientServiceMock) AddRmrRoute(params *AddRmrRouteParams) (*AddRmrRouteCreated, error) {
	args:= a.Called(params)

	return args.Get(0).(*AddRmrRouteCreated),nil
}

func (a *ClientServiceMock) AssociateRanToE2tHandle(params *AssociateRanToE2tHandleParams) (*AssociateRanToE2tHandleCreated, error) {
	args:= a.Called(params)

	return args.Get(0).(*AssociateRanToE2tHandleCreated),nil
}

func (a *ClientServiceMock) CreateNewE2tHandle(params *CreateNewE2tHandleParams) (*CreateNewE2tHandleCreated, error) {
	args:= a.Called(params)

	return args.Get(0).(*CreateNewE2tHandleCreated),nil
}

func (a *ClientServiceMock) DelRmrRoute(params *DelRmrRouteParams) (*DelRmrRouteCreated, error) {
	args:= a.Called(params)

	return args.Get(0).(*DelRmrRouteCreated),nil
}

func (a *ClientServiceMock) DeleteE2tHandle(params *DeleteE2tHandleParams) (*DeleteE2tHandleCreated, error) {
	args:= a.Called(params)

	return args.Get(0).(*DeleteE2tHandleCreated),nil
}

func (a *ClientServiceMock) DeleteXappSubscriptionHandle(params *DeleteXappSubscriptionHandleParams) (*DeleteXappSubscriptionHandleOK, *DeleteXappSubscriptionHandleNoContent, error) {
	args:= a.Called(params)

	return args.Get(0).(*DeleteXappSubscriptionHandleOK),args.Get(1).(*DeleteXappSubscriptionHandleNoContent),nil
}

func (a *ClientServiceMock) DissociateRan(params *DissociateRanParams) (*DissociateRanCreated, error) {
	args:= a.Called(params)

	return args.Get(0).(*DissociateRanCreated),nil
}

func (a *ClientServiceMock) GetHandles(params *GetHandlesParams) (*GetHandlesOK, error) {
	args:= a.Called(params)

	return args.Get(0).(*GetHandlesOK),nil
}

func (a *ClientServiceMock) ProvideXappHandle(params *ProvideXappHandleParams) (*ProvideXappHandleCreated, error) {
	args:= a.Called(params)

	return args.Get(0).(*ProvideXappHandleCreated),nil
}

func (a *ClientServiceMock) UpdateXappSubscriptionHandle(params *UpdateXappSubscriptionHandleParams) (*UpdateXappSubscriptionHandleCreated, error) {
	args:= a.Called(params)

	return args.Get(0).(*UpdateXappSubscriptionHandleCreated),nil
}

func (a *ClientServiceMock) SetTransport(transport runtime.ClientTransport) {
	a.Called(transport)

	return
}

func (a *ClientServiceMock) ProvideXappSubscriptionHandle(params *ProvideXappSubscriptionHandleParams) (*ProvideXappSubscriptionHandleCreated, error) {
	args:= a.Called(params)

	return args.Get(0).(*ProvideXappSubscriptionHandleCreated),nil
}