/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-IEs"
 * 	found in "Spec/e2ap-v031ex.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_CellReportingIndicator_H_
#define	_CellReportingIndicator_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CellReportingIndicator {
	CellReportingIndicator_stop_request	= 0
	/*
	 * Enumeration is extensible
	 */
} e_CellReportingIndicator;

/* CellReportingIndicator */
typedef long	 CellReportingIndicator_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CellReportingIndicator;
asn_struct_free_f CellReportingIndicator_free;
asn_struct_print_f CellReportingIndicator_print;
asn_constr_check_f CellReportingIndicator_constraint;
ber_type_decoder_f CellReportingIndicator_decode_ber;
der_type_encoder_f CellReportingIndicator_encode_der;
xer_type_decoder_f CellReportingIndicator_decode_xer;
xer_type_encoder_f CellReportingIndicator_encode_xer;
oer_type_decoder_f CellReportingIndicator_decode_oer;
oer_type_encoder_f CellReportingIndicator_encode_oer;
per_type_decoder_f CellReportingIndicator_decode_uper;
per_type_encoder_f CellReportingIndicator_encode_uper;
per_type_decoder_f CellReportingIndicator_decode_aper;
per_type_encoder_f CellReportingIndicator_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _CellReportingIndicator_H_ */
#include <asn_internal.h>
