/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-IEs"
 * 	found in "Spec/e2ap-v031ex.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_CNTypeRestrictionsItem_H_
#define	_CNTypeRestrictionsItem_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PLMN-Identity.h"
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CNTypeRestrictionsItem__cn_type {
	CNTypeRestrictionsItem__cn_type_fiveGC_forbidden	= 0
	/*
	 * Enumeration is extensible
	 */
} e_CNTypeRestrictionsItem__cn_type;

/* Forward declarations */
struct ProtocolExtensionContainer;

/* CNTypeRestrictionsItem */
typedef struct CNTypeRestrictionsItem {
	PLMN_Identity_t	 plmn_Id;
	long	 cn_type;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CNTypeRestrictionsItem_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_cn_type_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_CNTypeRestrictionsItem;
extern asn_SEQUENCE_specifics_t asn_SPC_CNTypeRestrictionsItem_specs_1;
extern asn_TYPE_member_t asn_MBR_CNTypeRestrictionsItem_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _CNTypeRestrictionsItem_H_ */
#include <asn_internal.h>
