/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-IEs"
 * 	found in "X2AP-15-4-0.asn1"
 * 	`asn1c -D ./asn1_n1 -pdu=auto -fno-include-deps -fcompound-names -findirect-choice -gen-PER -gen-OER -no-gen-example`
 */

#ifndef	_CoMPHypothesisSet_H_
#define	_CoMPHypothesisSet_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CoMPHypothesisSetItem;

/* CoMPHypothesisSet */
typedef struct CoMPHypothesisSet {
	A_SEQUENCE_OF(struct CoMPHypothesisSetItem) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CoMPHypothesisSet_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CoMPHypothesisSet;
extern asn_SET_OF_specifics_t asn_SPC_CoMPHypothesisSet_specs_1;
extern asn_TYPE_member_t asn_MBR_CoMPHypothesisSet_1[1];
extern asn_per_constraints_t asn_PER_type_CoMPHypothesisSet_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _CoMPHypothesisSet_H_ */
#include <asn_internal.h>
