/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-IEs"
 * 	found in "Spec/e2ap-v031ex.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_CyclicPrefixDL_H_
#define	_CyclicPrefixDL_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CyclicPrefixDL {
	CyclicPrefixDL_normal	= 0,
	CyclicPrefixDL_extended	= 1
	/*
	 * Enumeration is extensible
	 */
} e_CyclicPrefixDL;

/* CyclicPrefixDL */
typedef long	 CyclicPrefixDL_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_CyclicPrefixDL_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_CyclicPrefixDL;
extern const asn_INTEGER_specifics_t asn_SPC_CyclicPrefixDL_specs_1;
asn_struct_free_f CyclicPrefixDL_free;
asn_struct_print_f CyclicPrefixDL_print;
asn_constr_check_f CyclicPrefixDL_constraint;
ber_type_decoder_f CyclicPrefixDL_decode_ber;
der_type_encoder_f CyclicPrefixDL_encode_der;
xer_type_decoder_f CyclicPrefixDL_decode_xer;
xer_type_encoder_f CyclicPrefixDL_encode_xer;
oer_type_decoder_f CyclicPrefixDL_decode_oer;
oer_type_encoder_f CyclicPrefixDL_encode_oer;
per_type_decoder_f CyclicPrefixDL_decode_uper;
per_type_encoder_f CyclicPrefixDL_encode_uper;
per_type_decoder_f CyclicPrefixDL_decode_aper;
per_type_encoder_f CyclicPrefixDL_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _CyclicPrefixDL_H_ */
#include <asn_internal.h>
