/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-IEs"
 * 	found in "Spec/e2ap-v031ex.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_DynamicDLTransmissionInformation_H_
#define	_DynamicDLTransmissionInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DynamicDLTransmissionInformation_PR {
	DynamicDLTransmissionInformation_PR_NOTHING,	/* No components present */
	DynamicDLTransmissionInformation_PR_naics_active,
	DynamicDLTransmissionInformation_PR_naics_inactive
	/* Extensions may appear below */
	
} DynamicDLTransmissionInformation_PR;

/* Forward declarations */
struct DynamicNAICSInformation;

/* DynamicDLTransmissionInformation */
typedef struct DynamicDLTransmissionInformation {
	DynamicDLTransmissionInformation_PR present;
	union DynamicDLTransmissionInformation_u {
		struct DynamicNAICSInformation	*naics_active;
		NULL_t	 naics_inactive;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DynamicDLTransmissionInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DynamicDLTransmissionInformation;

#ifdef __cplusplus
}
#endif

#endif	/* _DynamicDLTransmissionInformation_H_ */
#include <asn_internal.h>
