/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-PDU-Contents"
 * 	found in "Spec/e2ap-v031ex.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_E_RABs_ToBeSetup_Item_H_
#define	_E_RABs_ToBeSetup_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "E-RAB-ID.h"
#include "E-RAB-Level-QoS-Parameters.h"
#include "DL-Forwarding.h"
#include "GTPtunnelEndpoint.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* E-RABs-ToBeSetup-Item */
typedef struct E_RABs_ToBeSetup_Item {
	E_RAB_ID_t	 e_RAB_ID;
	E_RAB_Level_QoS_Parameters_t	 e_RAB_Level_QoS_Parameters;
	DL_Forwarding_t	*dL_Forwarding;	/* OPTIONAL */
	GTPtunnelEndpoint_t	 uL_GTPtunnelEndpoint;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E_RABs_ToBeSetup_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E_RABs_ToBeSetup_Item;

#ifdef __cplusplus
}
#endif

#endif	/* _E_RABs_ToBeSetup_Item_H_ */
#include <asn_internal.h>
