/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-PDU-Contents"
 * 	found in "X2AP-15-4-0.asn1"
 * 	`asn1c -D ./asn1_n1 -pdu=auto -fno-include-deps -fcompound-names -findirect-choice -gen-PER -gen-OER -no-gen-example`
 */

#ifndef	_E_RABs_ToBeModified_SgNBModReqd_Item_SgNBPDCPnotpresent_H_
#define	_E_RABs_ToBeModified_SgNBModReqd_Item_SgNBPDCPnotpresent_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct GTPtunnelEndpoint;
struct ProtocolExtensionContainer;

/* E-RABs-ToBeModified-SgNBModReqd-Item-SgNBPDCPnotpresent */
typedef struct E_RABs_ToBeModified_SgNBModReqd_Item_SgNBPDCPnotpresent {
	struct GTPtunnelEndpoint	*sgNB_DL_GTP_TEIDatSCG;	/* OPTIONAL */
	struct GTPtunnelEndpoint	*secondary_sgNB_DL_GTP_TEIDatSCG;	/* OPTIONAL */
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E_RABs_ToBeModified_SgNBModReqd_Item_SgNBPDCPnotpresent_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E_RABs_ToBeModified_SgNBModReqd_Item_SgNBPDCPnotpresent;
extern asn_SEQUENCE_specifics_t asn_SPC_E_RABs_ToBeModified_SgNBModReqd_Item_SgNBPDCPnotpresent_specs_1;
extern asn_TYPE_member_t asn_MBR_E_RABs_ToBeModified_SgNBModReqd_Item_SgNBPDCPnotpresent_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _E_RABs_ToBeModified_SgNBModReqd_Item_SgNBPDCPnotpresent_H_ */
#include <asn_internal.h>
