/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-PDU-Contents"
 * 	found in "Spec/e2ap-v031ex.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_ENDCX2RemovalFailure_H_
#define	_ENDCX2RemovalFailure_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ProtocolIE-Container.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ENDCX2RemovalFailure */
typedef struct ENDCX2RemovalFailure {
	ProtocolIE_Container_9515P117_t	 protocolIEs;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ENDCX2RemovalFailure_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ENDCX2RemovalFailure;
extern asn_SEQUENCE_specifics_t asn_SPC_ENDCX2RemovalFailure_specs_1;
extern asn_TYPE_member_t asn_MBR_ENDCX2RemovalFailure_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _ENDCX2RemovalFailure_H_ */
#include <asn_internal.h>
