/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-IEs"
 * 	found in "Spec/e2ap-v031ex.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_EUTRANTraceID_H_
#define	_EUTRANTraceID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EUTRANTraceID */
typedef OCTET_STRING_t	 EUTRANTraceID_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_EUTRANTraceID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_EUTRANTraceID;
asn_struct_free_f EUTRANTraceID_free;
asn_struct_print_f EUTRANTraceID_print;
asn_constr_check_f EUTRANTraceID_constraint;
ber_type_decoder_f EUTRANTraceID_decode_ber;
der_type_encoder_f EUTRANTraceID_encode_der;
xer_type_decoder_f EUTRANTraceID_decode_xer;
xer_type_encoder_f EUTRANTraceID_encode_xer;
oer_type_decoder_f EUTRANTraceID_decode_oer;
oer_type_encoder_f EUTRANTraceID_encode_oer;
per_type_decoder_f EUTRANTraceID_decode_uper;
per_type_encoder_f EUTRANTraceID_encode_uper;
per_type_decoder_f EUTRANTraceID_decode_aper;
per_type_encoder_f EUTRANTraceID_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _EUTRANTraceID_H_ */
#include <asn_internal.h>
