/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-IEs"
 * 	found in "Spec/e2ap-v031ex.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_ExtendedULInterferenceOverloadInfo_H_
#define	_ExtendedULInterferenceOverloadInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include "UL-InterferenceOverloadIndication.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* ExtendedULInterferenceOverloadInfo */
typedef struct ExtendedULInterferenceOverloadInfo {
	BIT_STRING_t	 associatedSubframes;
	UL_InterferenceOverloadIndication_t	 extended_ul_InterferenceOverloadIndication;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ExtendedULInterferenceOverloadInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ExtendedULInterferenceOverloadInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _ExtendedULInterferenceOverloadInfo_H_ */
#include <asn_internal.h>
