/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-IEs"
 * 	found in "Spec/e2ap-v031ex.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_Fourframes_H_
#define	_Fourframes_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Fourframes */
typedef BIT_STRING_t	 Fourframes_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Fourframes_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Fourframes;
asn_struct_free_f Fourframes_free;
asn_struct_print_f Fourframes_print;
asn_constr_check_f Fourframes_constraint;
ber_type_decoder_f Fourframes_decode_ber;
der_type_encoder_f Fourframes_encode_der;
xer_type_decoder_f Fourframes_decode_xer;
xer_type_encoder_f Fourframes_encode_xer;
oer_type_decoder_f Fourframes_decode_oer;
oer_type_encoder_f Fourframes_encode_oer;
per_type_decoder_f Fourframes_decode_uper;
per_type_encoder_f Fourframes_encode_uper;
per_type_decoder_f Fourframes_decode_aper;
per_type_encoder_f Fourframes_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Fourframes_H_ */
#include <asn_internal.h>
