/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-IEs"
 * 	found in "Spec/e2ap-v031ex.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_HandoverReportType_H_
#define	_HandoverReportType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HandoverReportType {
	HandoverReportType_hoTooEarly	= 0,
	HandoverReportType_hoToWrongCell	= 1,
	/*
	 * Enumeration is extensible
	 */
	HandoverReportType_interRATpingpong	= 2
} e_HandoverReportType;

/* HandoverReportType */
typedef long	 HandoverReportType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HandoverReportType;
asn_struct_free_f HandoverReportType_free;
asn_struct_print_f HandoverReportType_print;
asn_constr_check_f HandoverReportType_constraint;
ber_type_decoder_f HandoverReportType_decode_ber;
der_type_encoder_f HandoverReportType_encode_der;
xer_type_decoder_f HandoverReportType_decode_xer;
xer_type_encoder_f HandoverReportType_encode_xer;
oer_type_decoder_f HandoverReportType_decode_oer;
oer_type_encoder_f HandoverReportType_encode_oer;
per_type_decoder_f HandoverReportType_decode_uper;
per_type_encoder_f HandoverReportType_encode_uper;
per_type_decoder_f HandoverReportType_decode_aper;
per_type_encoder_f HandoverReportType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _HandoverReportType_H_ */
#include <asn_internal.h>
