/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-PDU-Contents"
 * 	found in "Spec/e2ap-v031ex.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_InitiatingNodeType_EndcX2Setup_H_
#define	_InitiatingNodeType_EndcX2Setup_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum InitiatingNodeType_EndcX2Setup_PR {
	InitiatingNodeType_EndcX2Setup_PR_NOTHING,	/* No components present */
	InitiatingNodeType_EndcX2Setup_PR_init_eNB,
	InitiatingNodeType_EndcX2Setup_PR_init_en_gNB
	/* Extensions may appear below */
	
} InitiatingNodeType_EndcX2Setup_PR;

/* Forward declarations */
struct ProtocolIE_Container;

/* InitiatingNodeType-EndcX2Setup */
typedef struct InitiatingNodeType_EndcX2Setup {
	InitiatingNodeType_EndcX2Setup_PR present;
	union InitiatingNodeType_EndcX2Setup_u {
		struct ProtocolIE_Container	*init_eNB;
		struct ProtocolIE_Container	*init_en_gNB;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InitiatingNodeType_EndcX2Setup_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InitiatingNodeType_EndcX2Setup;

#ifdef __cplusplus
}
#endif

#endif	/* _InitiatingNodeType_EndcX2Setup_H_ */
#include <asn_internal.h>
