/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-PDU-Contents"
 * 	found in "X2AP-15-4-0.asn1"
 * 	`asn1c -D ./asn1_n1 -pdu=auto -fno-include-deps -fcompound-names -findirect-choice -gen-PER -gen-OER -no-gen-example`
 */

#ifndef	_InitiatingNodeType_EutranrCellResourceCoordination_H_
#define	_InitiatingNodeType_EutranrCellResourceCoordination_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum InitiatingNodeType_EutranrCellResourceCoordination_PR {
	InitiatingNodeType_EutranrCellResourceCoordination_PR_NOTHING,	/* No components present */
	InitiatingNodeType_EutranrCellResourceCoordination_PR_initiate_eNB,
	InitiatingNodeType_EutranrCellResourceCoordination_PR_initiate_en_gNB
	/* Extensions may appear below */
	
} InitiatingNodeType_EutranrCellResourceCoordination_PR;

/* Forward declarations */
struct ProtocolIE_Container;

/* InitiatingNodeType-EutranrCellResourceCoordination */
typedef struct InitiatingNodeType_EutranrCellResourceCoordination {
	InitiatingNodeType_EutranrCellResourceCoordination_PR present;
	union InitiatingNodeType_EutranrCellResourceCoordination_u {
		struct ProtocolIE_Container	*initiate_eNB;
		struct ProtocolIE_Container	*initiate_en_gNB;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InitiatingNodeType_EutranrCellResourceCoordination_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InitiatingNodeType_EutranrCellResourceCoordination;

#ifdef __cplusplus
}
#endif

#endif	/* _InitiatingNodeType_EutranrCellResourceCoordination_H_ */
#include <asn_internal.h>
