/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-gNB-X2-IEs"
 * 	found in "Spec/e2ap-v031ex.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_InterfaceMessageType_H_
#define	_InterfaceMessageType_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ProcedureCode.h"
#include "TypeOfMessage.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* InterfaceMessageType */
typedef struct InterfaceMessageType {
	ProcedureCode_t	 procedureCode;
	TypeOfMessage_t	 typeOfMessage;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InterfaceMessageType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InterfaceMessageType;
extern asn_SEQUENCE_specifics_t asn_SPC_InterfaceMessageType_specs_1;
extern asn_TYPE_member_t asn_MBR_InterfaceMessageType_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _InterfaceMessageType_H_ */
#include <asn_internal.h>
