/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-IEs"
 * 	found in "Spec/e2ap-v031ex.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_MakeBeforeBreakIndicator_H_
#define	_MakeBeforeBreakIndicator_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MakeBeforeBreakIndicator {
	MakeBeforeBreakIndicator_true	= 0
	/*
	 * Enumeration is extensible
	 */
} e_MakeBeforeBreakIndicator;

/* MakeBeforeBreakIndicator */
typedef long	 MakeBeforeBreakIndicator_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MakeBeforeBreakIndicator;
asn_struct_free_f MakeBeforeBreakIndicator_free;
asn_struct_print_f MakeBeforeBreakIndicator_print;
asn_constr_check_f MakeBeforeBreakIndicator_constraint;
ber_type_decoder_f MakeBeforeBreakIndicator_decode_ber;
der_type_encoder_f MakeBeforeBreakIndicator_encode_der;
xer_type_decoder_f MakeBeforeBreakIndicator_decode_xer;
xer_type_encoder_f MakeBeforeBreakIndicator_encode_xer;
oer_type_decoder_f MakeBeforeBreakIndicator_decode_oer;
oer_type_encoder_f MakeBeforeBreakIndicator_encode_oer;
per_type_decoder_f MakeBeforeBreakIndicator_decode_uper;
per_type_encoder_f MakeBeforeBreakIndicator_encode_uper;
per_type_decoder_f MakeBeforeBreakIndicator_decode_aper;
per_type_encoder_f MakeBeforeBreakIndicator_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _MakeBeforeBreakIndicator_H_ */
#include <asn_internal.h>
