/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-IEs"
 * 	found in "Spec/e2ap-v031ex.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_MBSFN_Subframe_Info_H_
#define	_MBSFN_Subframe_Info_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RadioframeAllocationPeriod.h"
#include "RadioframeAllocationOffset.h"
#include "SubframeAllocation.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* MBSFN-Subframe-Info */
typedef struct MBSFN_Subframe_Info {
	RadioframeAllocationPeriod_t	 radioframeAllocationPeriod;
	RadioframeAllocationOffset_t	 radioframeAllocationOffset;
	SubframeAllocation_t	 subframeAllocation;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MBSFN_Subframe_Info_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MBSFN_Subframe_Info;
extern asn_SEQUENCE_specifics_t asn_SPC_MBSFN_Subframe_Info_specs_1;
extern asn_TYPE_member_t asn_MBR_MBSFN_Subframe_Info_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _MBSFN_Subframe_Info_H_ */
#include <asn_internal.h>
