/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-PDU-Contents"
 * 	found in "Spec/e2ap-v031ex.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_MeasurementInitiationResult_Item_H_
#define	_MeasurementInitiationResult_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ECGI.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MeasurementFailureCause_List;
struct ProtocolExtensionContainer;

/* MeasurementInitiationResult-Item */
typedef struct MeasurementInitiationResult_Item {
	ECGI_t	 cell_ID;
	struct MeasurementFailureCause_List	*measurementFailureCause_List;	/* OPTIONAL */
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasurementInitiationResult_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasurementInitiationResult_Item;

#ifdef __cplusplus
}
#endif

#endif	/* _MeasurementInitiationResult_Item_H_ */
#include <asn_internal.h>
