/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-IEs"
 * 	found in "Spec/e2ap-v031ex.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_NRS_NSSS_PowerOffset_H_
#define	_NRS_NSSS_PowerOffset_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRS_NSSS_PowerOffset {
	NRS_NSSS_PowerOffset_minusThree	= 0,
	NRS_NSSS_PowerOffset_zero	= 1,
	NRS_NSSS_PowerOffset_three	= 2
	/*
	 * Enumeration is extensible
	 */
} e_NRS_NSSS_PowerOffset;

/* NRS-NSSS-PowerOffset */
typedef long	 NRS_NSSS_PowerOffset_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRS_NSSS_PowerOffset;
asn_struct_free_f NRS_NSSS_PowerOffset_free;
asn_struct_print_f NRS_NSSS_PowerOffset_print;
asn_constr_check_f NRS_NSSS_PowerOffset_constraint;
ber_type_decoder_f NRS_NSSS_PowerOffset_decode_ber;
der_type_encoder_f NRS_NSSS_PowerOffset_encode_der;
xer_type_decoder_f NRS_NSSS_PowerOffset_decode_xer;
xer_type_encoder_f NRS_NSSS_PowerOffset_encode_xer;
oer_type_decoder_f NRS_NSSS_PowerOffset_decode_oer;
oer_type_encoder_f NRS_NSSS_PowerOffset_encode_oer;
per_type_decoder_f NRS_NSSS_PowerOffset_decode_uper;
per_type_encoder_f NRS_NSSS_PowerOffset_encode_uper;
per_type_decoder_f NRS_NSSS_PowerOffset_decode_aper;
per_type_encoder_f NRS_NSSS_PowerOffset_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NRS_NSSS_PowerOffset_H_ */
#include <asn_internal.h>
