/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-IEs"
 * 	found in "X2AP-15-4-0.asn1"
 * 	`asn1c -D ./asn1_n1 -pdu=auto -fno-include-deps -fcompound-names -findirect-choice -gen-PER -gen-OER -no-gen-example`
 */

#ifndef	_ProtectedResourceList_Item_H_
#define	_ProtectedResourceList_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ResourceType.h"
#include <BIT_STRING.h>
#include "ProtectedFootprintTimePattern.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* ProtectedResourceList-Item */
typedef struct ProtectedResourceList_Item {
	ResourceType_t	 resourceType;
	BIT_STRING_t	 intraPRBProtectedResourceFootprint;
	BIT_STRING_t	 protectedFootprintFrequencyPattern;
	ProtectedFootprintTimePattern_t	 protectedFootprintTimePattern;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtectedResourceList_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProtectedResourceList_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtectedResourceList_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_ProtectedResourceList_Item_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _ProtectedResourceList_Item_H_ */
#include <asn_internal.h>
