/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-Containers"
 * 	found in "Spec/e2ap-v031ex.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_ProtocolIE_Container_H_
#define	_ProtocolIE_Container_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RICsubscriptionRequest_IEs;
struct RICsubscriptionResponse_IEs;
struct RICsubscriptionFailure_IEs;
struct RICsubscriptionDeleteRequest_IEs;
struct RICsubscriptionDeleteResponse_IEs;
struct RICsubscriptionDeleteFailure_IEs;
struct RICindication_IEs;
struct RICcontrolRequest_IEs;
struct RICcontrolAcknowledge_IEs;
struct RICcontrolFailure_IEs;
struct RICserviceUpdate_IEs;
struct RICserviceUpdateAcknowledge_IEs;
struct RICserviceUpdateFailure_IEs;
struct RICserviceQuery_IEs;
struct HandoverRequest_IEs;
struct HandoverRequestAcknowledge_IEs;
struct HandoverPreparationFailure_IEs;
struct HandoverReport_IEs;
struct SNStatusTransfer_IEs;
struct UEContextRelease_IEs;
struct HandoverCancel_IEs;
struct ErrorIndication_IEs;
struct ResetRequest_IEs;
struct ResetResponse_IEs;
struct X2SetupRequest_IEs;
struct X2SetupResponse_IEs;
struct X2SetupFailure_IEs;
struct LoadInformation_IEs;
struct ENBConfigurationUpdate_IEs;
struct ENBConfigurationUpdateAcknowledge_IEs;
struct ENBConfigurationUpdateFailure_IEs;
struct ResourceStatusRequest_IEs;
struct ResourceStatusResponse_IEs;
struct ResourceStatusFailure_IEs;
struct ResourceStatusUpdate_IEs;
struct MobilityChangeRequest_IEs;
struct MobilityChangeAcknowledge_IEs;
struct MobilityChangeFailure_IEs;
struct RLFIndication_IEs;
struct CellActivationRequest_IEs;
struct CellActivationResponse_IEs;
struct CellActivationFailure_IEs;
struct X2Release_IEs;
struct X2APMessageTransfer_IEs;
struct SeNBAdditionRequest_IEs;
struct SeNBAdditionRequestAcknowledge_IEs;
struct SeNBAdditionRequestReject_IEs;
struct SeNBReconfigurationComplete_IEs;
struct SeNBModificationRequest_IEs;
struct SeNBModificationRequestAcknowledge_IEs;
struct SeNBModificationRequestReject_IEs;
struct SeNBModificationRequired_IEs;
struct SeNBModificationConfirm_IEs;
struct SeNBModificationRefuse_IEs;
struct SeNBReleaseRequest_IEs;
struct SeNBReleaseRequired_IEs;
struct SeNBReleaseConfirm_IEs;
struct SeNBCounterCheckRequest_IEs;
struct X2RemovalRequest_IEs;
struct X2RemovalResponse_IEs;
struct X2RemovalFailure_IEs;
struct RetrieveUEContextRequest_IEs;
struct RetrieveUEContextResponse_IEs;
struct RetrieveUEContextFailure_IEs;
struct SgNBAdditionRequest_IEs;
struct SgNBAdditionRequestAcknowledge_IEs;
struct SgNBAdditionRequestReject_IEs;
struct SgNBReconfigurationComplete_IEs;
struct SgNBModificationRequest_IEs;
struct SgNBModificationRequestAcknowledge_IEs;
struct SgNBModificationRequestReject_IEs;
struct SgNBModificationRequired_IEs;
struct SgNBModificationConfirm_IEs;
struct SgNBModificationRefuse_IEs;
struct SgNBReleaseRequest_IEs;
struct SgNBReleaseRequestAcknowledge_IEs;
struct SgNBReleaseRequestReject_IEs;
struct SgNBReleaseRequired_IEs;
struct SgNBReleaseConfirm_IEs;
struct SgNBCounterCheckRequest_IEs;
struct SgNBChangeRequired_IEs;
struct SgNBChangeConfirm_IEs;
struct RRCTransfer_IEs;
struct SgNBChangeRefuse_IEs;
struct ENDCX2SetupRequest_IEs;
struct ENB_ENDCX2SetupReqIEs;
struct En_gNB_ENDCX2SetupReqIEs;
struct ENDCX2SetupResponse_IEs;
struct ENB_ENDCX2SetupReqAckIEs;
struct En_gNB_ENDCX2SetupReqAckIEs;
struct ENDCX2SetupFailure_IEs;
struct ENDCConfigurationUpdate_IEs;
struct ENB_ENDCConfigUpdateIEs;
struct En_gNB_ENDCConfigUpdateIEs;
struct ENDCConfigurationUpdateAcknowledge_IEs;
struct ENB_ENDCConfigUpdateAckIEs;
struct En_gNB_ENDCConfigUpdateAckIEs;
struct ENDCConfigurationUpdateFailure_IEs;
struct ENDCCellActivationRequest_IEs;
struct ENDCCellActivationResponse_IEs;
struct ENDCCellActivationFailure_IEs;
struct SecondaryRATDataUsageReport_IEs;
struct SgNBActivityNotification_IEs;
struct ENDCPartialResetRequired_IEs;
struct ENDCPartialResetConfirm_IEs;
struct EUTRANRCellResourceCoordinationRequest_IEs;
struct ENB_EUTRA_NRCellResourceCoordinationReqIEs;
struct En_gNB_EUTRA_NRCellResourceCoordinationReqIEs;
struct EUTRANRCellResourceCoordinationResponse_IEs;
struct ENB_EUTRA_NRCellResourceCoordinationReqAckIEs;
struct En_gNB_EUTRA_NRCellResourceCoordinationReqAckIEs;
struct ENDCX2RemovalRequest_IEs;
struct ENB_ENDCX2RemovalReqIEs;
struct En_gNB_ENDCX2RemovalReqIEs;
struct ENDCX2RemovalResponse_IEs;
struct ENB_ENDCX2RemovalReqAckIEs;
struct En_gNB_ENDCX2RemovalReqAckIEs;
struct ENDCX2RemovalFailure_IEs;
struct DataForwardingAddressIndication_IEs;
struct GNBStatusIndicationIEs;

/* ProtocolIE-Container */
typedef struct ProtocolIE_Container_9515P0 {
	A_SEQUENCE_OF(struct RICsubscriptionRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P0_t;
typedef struct ProtocolIE_Container_9515P1 {
	A_SEQUENCE_OF(struct RICsubscriptionResponse_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P1_t;
typedef struct ProtocolIE_Container_9515P2 {
	A_SEQUENCE_OF(struct RICsubscriptionFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P2_t;
typedef struct ProtocolIE_Container_9515P3 {
	A_SEQUENCE_OF(struct RICsubscriptionDeleteRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P3_t;
typedef struct ProtocolIE_Container_9515P4 {
	A_SEQUENCE_OF(struct RICsubscriptionDeleteResponse_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P4_t;
typedef struct ProtocolIE_Container_9515P5 {
	A_SEQUENCE_OF(struct RICsubscriptionDeleteFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P5_t;
typedef struct ProtocolIE_Container_9515P6 {
	A_SEQUENCE_OF(struct RICindication_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P6_t;
typedef struct ProtocolIE_Container_9515P7 {
	A_SEQUENCE_OF(struct RICcontrolRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P7_t;
typedef struct ProtocolIE_Container_9515P8 {
	A_SEQUENCE_OF(struct RICcontrolAcknowledge_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P8_t;
typedef struct ProtocolIE_Container_9515P9 {
	A_SEQUENCE_OF(struct RICcontrolFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P9_t;
typedef struct ProtocolIE_Container_9515P10 {
	A_SEQUENCE_OF(struct RICserviceUpdate_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P10_t;
typedef struct ProtocolIE_Container_9515P11 {
	A_SEQUENCE_OF(struct RICserviceUpdateAcknowledge_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P11_t;
typedef struct ProtocolIE_Container_9515P12 {
	A_SEQUENCE_OF(struct RICserviceUpdateFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P12_t;
typedef struct ProtocolIE_Container_9515P13 {
	A_SEQUENCE_OF(struct RICserviceQuery_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P13_t;
typedef struct ProtocolIE_Container_9515P14 {
	A_SEQUENCE_OF(struct HandoverRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P14_t;
typedef struct ProtocolIE_Container_9515P15 {
	A_SEQUENCE_OF(struct HandoverRequestAcknowledge_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P15_t;
typedef struct ProtocolIE_Container_9515P16 {
	A_SEQUENCE_OF(struct HandoverPreparationFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P16_t;
typedef struct ProtocolIE_Container_9515P17 {
	A_SEQUENCE_OF(struct HandoverReport_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P17_t;
typedef struct ProtocolIE_Container_9515P18 {
	A_SEQUENCE_OF(struct SNStatusTransfer_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P18_t;
typedef struct ProtocolIE_Container_9515P19 {
	A_SEQUENCE_OF(struct UEContextRelease_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P19_t;
typedef struct ProtocolIE_Container_9515P20 {
	A_SEQUENCE_OF(struct HandoverCancel_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P20_t;
typedef struct ProtocolIE_Container_9515P21 {
	A_SEQUENCE_OF(struct ErrorIndication_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P21_t;
typedef struct ProtocolIE_Container_9515P22 {
	A_SEQUENCE_OF(struct ResetRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P22_t;
typedef struct ProtocolIE_Container_9515P23 {
	A_SEQUENCE_OF(struct ResetResponse_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P23_t;
typedef struct ProtocolIE_Container_9515P24 {
	A_SEQUENCE_OF(struct X2SetupRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P24_t;
typedef struct ProtocolIE_Container_9515P25 {
	A_SEQUENCE_OF(struct X2SetupResponse_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P25_t;
typedef struct ProtocolIE_Container_9515P26 {
	A_SEQUENCE_OF(struct X2SetupFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P26_t;
typedef struct ProtocolIE_Container_9515P27 {
	A_SEQUENCE_OF(struct LoadInformation_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P27_t;
typedef struct ProtocolIE_Container_9515P28 {
	A_SEQUENCE_OF(struct ENBConfigurationUpdate_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P28_t;
typedef struct ProtocolIE_Container_9515P29 {
	A_SEQUENCE_OF(struct ENBConfigurationUpdateAcknowledge_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P29_t;
typedef struct ProtocolIE_Container_9515P30 {
	A_SEQUENCE_OF(struct ENBConfigurationUpdateFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P30_t;
typedef struct ProtocolIE_Container_9515P31 {
	A_SEQUENCE_OF(struct ResourceStatusRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P31_t;
typedef struct ProtocolIE_Container_9515P32 {
	A_SEQUENCE_OF(struct ResourceStatusResponse_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P32_t;
typedef struct ProtocolIE_Container_9515P33 {
	A_SEQUENCE_OF(struct ResourceStatusFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P33_t;
typedef struct ProtocolIE_Container_9515P34 {
	A_SEQUENCE_OF(struct ResourceStatusUpdate_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P34_t;
typedef struct ProtocolIE_Container_9515P35 {
	A_SEQUENCE_OF(struct MobilityChangeRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P35_t;
typedef struct ProtocolIE_Container_9515P36 {
	A_SEQUENCE_OF(struct MobilityChangeAcknowledge_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P36_t;
typedef struct ProtocolIE_Container_9515P37 {
	A_SEQUENCE_OF(struct MobilityChangeFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P37_t;
typedef struct ProtocolIE_Container_9515P38 {
	A_SEQUENCE_OF(struct RLFIndication_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P38_t;
typedef struct ProtocolIE_Container_9515P39 {
	A_SEQUENCE_OF(struct CellActivationRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P39_t;
typedef struct ProtocolIE_Container_9515P40 {
	A_SEQUENCE_OF(struct CellActivationResponse_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P40_t;
typedef struct ProtocolIE_Container_9515P41 {
	A_SEQUENCE_OF(struct CellActivationFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P41_t;
typedef struct ProtocolIE_Container_9515P42 {
	A_SEQUENCE_OF(struct X2Release_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P42_t;
typedef struct ProtocolIE_Container_9515P43 {
	A_SEQUENCE_OF(struct X2APMessageTransfer_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P43_t;
typedef struct ProtocolIE_Container_9515P44 {
	A_SEQUENCE_OF(struct SeNBAdditionRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P44_t;
typedef struct ProtocolIE_Container_9515P45 {
	A_SEQUENCE_OF(struct SeNBAdditionRequestAcknowledge_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P45_t;
typedef struct ProtocolIE_Container_9515P46 {
	A_SEQUENCE_OF(struct SeNBAdditionRequestReject_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P46_t;
typedef struct ProtocolIE_Container_9515P47 {
	A_SEQUENCE_OF(struct SeNBReconfigurationComplete_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P47_t;
typedef struct ProtocolIE_Container_9515P48 {
	A_SEQUENCE_OF(struct SeNBModificationRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P48_t;
typedef struct ProtocolIE_Container_9515P49 {
	A_SEQUENCE_OF(struct SeNBModificationRequestAcknowledge_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P49_t;
typedef struct ProtocolIE_Container_9515P50 {
	A_SEQUENCE_OF(struct SeNBModificationRequestReject_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P50_t;
typedef struct ProtocolIE_Container_9515P51 {
	A_SEQUENCE_OF(struct SeNBModificationRequired_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P51_t;
typedef struct ProtocolIE_Container_9515P52 {
	A_SEQUENCE_OF(struct SeNBModificationConfirm_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P52_t;
typedef struct ProtocolIE_Container_9515P53 {
	A_SEQUENCE_OF(struct SeNBModificationRefuse_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P53_t;
typedef struct ProtocolIE_Container_9515P54 {
	A_SEQUENCE_OF(struct SeNBReleaseRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P54_t;
typedef struct ProtocolIE_Container_9515P55 {
	A_SEQUENCE_OF(struct SeNBReleaseRequired_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P55_t;
typedef struct ProtocolIE_Container_9515P56 {
	A_SEQUENCE_OF(struct SeNBReleaseConfirm_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P56_t;
typedef struct ProtocolIE_Container_9515P57 {
	A_SEQUENCE_OF(struct SeNBCounterCheckRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P57_t;
typedef struct ProtocolIE_Container_9515P58 {
	A_SEQUENCE_OF(struct X2RemovalRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P58_t;
typedef struct ProtocolIE_Container_9515P59 {
	A_SEQUENCE_OF(struct X2RemovalResponse_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P59_t;
typedef struct ProtocolIE_Container_9515P60 {
	A_SEQUENCE_OF(struct X2RemovalFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P60_t;
typedef struct ProtocolIE_Container_9515P61 {
	A_SEQUENCE_OF(struct RetrieveUEContextRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P61_t;
typedef struct ProtocolIE_Container_9515P62 {
	A_SEQUENCE_OF(struct RetrieveUEContextResponse_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P62_t;
typedef struct ProtocolIE_Container_9515P63 {
	A_SEQUENCE_OF(struct RetrieveUEContextFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P63_t;
typedef struct ProtocolIE_Container_9515P64 {
	A_SEQUENCE_OF(struct SgNBAdditionRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P64_t;
typedef struct ProtocolIE_Container_9515P65 {
	A_SEQUENCE_OF(struct SgNBAdditionRequestAcknowledge_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P65_t;
typedef struct ProtocolIE_Container_9515P66 {
	A_SEQUENCE_OF(struct SgNBAdditionRequestReject_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P66_t;
typedef struct ProtocolIE_Container_9515P67 {
	A_SEQUENCE_OF(struct SgNBReconfigurationComplete_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P67_t;
typedef struct ProtocolIE_Container_9515P68 {
	A_SEQUENCE_OF(struct SgNBModificationRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P68_t;
typedef struct ProtocolIE_Container_9515P69 {
	A_SEQUENCE_OF(struct SgNBModificationRequestAcknowledge_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P69_t;
typedef struct ProtocolIE_Container_9515P70 {
	A_SEQUENCE_OF(struct SgNBModificationRequestReject_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P70_t;
typedef struct ProtocolIE_Container_9515P71 {
	A_SEQUENCE_OF(struct SgNBModificationRequired_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P71_t;
typedef struct ProtocolIE_Container_9515P72 {
	A_SEQUENCE_OF(struct SgNBModificationConfirm_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P72_t;
typedef struct ProtocolIE_Container_9515P73 {
	A_SEQUENCE_OF(struct SgNBModificationRefuse_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P73_t;
typedef struct ProtocolIE_Container_9515P74 {
	A_SEQUENCE_OF(struct SgNBReleaseRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P74_t;
typedef struct ProtocolIE_Container_9515P75 {
	A_SEQUENCE_OF(struct SgNBReleaseRequestAcknowledge_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P75_t;
typedef struct ProtocolIE_Container_9515P76 {
	A_SEQUENCE_OF(struct SgNBReleaseRequestReject_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P76_t;
typedef struct ProtocolIE_Container_9515P77 {
	A_SEQUENCE_OF(struct SgNBReleaseRequired_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P77_t;
typedef struct ProtocolIE_Container_9515P78 {
	A_SEQUENCE_OF(struct SgNBReleaseConfirm_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P78_t;
typedef struct ProtocolIE_Container_9515P79 {
	A_SEQUENCE_OF(struct SgNBCounterCheckRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P79_t;
typedef struct ProtocolIE_Container_9515P80 {
	A_SEQUENCE_OF(struct SgNBChangeRequired_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P80_t;
typedef struct ProtocolIE_Container_9515P81 {
	A_SEQUENCE_OF(struct SgNBChangeConfirm_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P81_t;
typedef struct ProtocolIE_Container_9515P82 {
	A_SEQUENCE_OF(struct RRCTransfer_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P82_t;
typedef struct ProtocolIE_Container_9515P83 {
	A_SEQUENCE_OF(struct SgNBChangeRefuse_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P83_t;
typedef struct ProtocolIE_Container_9515P84 {
	A_SEQUENCE_OF(struct ENDCX2SetupRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P84_t;
typedef struct ProtocolIE_Container_9515P85 {
	A_SEQUENCE_OF(struct ENB_ENDCX2SetupReqIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P85_t;
typedef struct ProtocolIE_Container_9515P86 {
	A_SEQUENCE_OF(struct En_gNB_ENDCX2SetupReqIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P86_t;
typedef struct ProtocolIE_Container_9515P87 {
	A_SEQUENCE_OF(struct ENDCX2SetupResponse_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P87_t;
typedef struct ProtocolIE_Container_9515P88 {
	A_SEQUENCE_OF(struct ENB_ENDCX2SetupReqAckIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P88_t;
typedef struct ProtocolIE_Container_9515P89 {
	A_SEQUENCE_OF(struct En_gNB_ENDCX2SetupReqAckIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P89_t;
typedef struct ProtocolIE_Container_9515P90 {
	A_SEQUENCE_OF(struct ENDCX2SetupFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P90_t;
typedef struct ProtocolIE_Container_9515P91 {
	A_SEQUENCE_OF(struct ENDCConfigurationUpdate_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P91_t;
typedef struct ProtocolIE_Container_9515P92 {
	A_SEQUENCE_OF(struct ENB_ENDCConfigUpdateIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P92_t;
typedef struct ProtocolIE_Container_9515P93 {
	A_SEQUENCE_OF(struct En_gNB_ENDCConfigUpdateIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P93_t;
typedef struct ProtocolIE_Container_9515P94 {
	A_SEQUENCE_OF(struct ENDCConfigurationUpdateAcknowledge_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P94_t;
typedef struct ProtocolIE_Container_9515P95 {
	A_SEQUENCE_OF(struct ENB_ENDCConfigUpdateAckIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P95_t;
typedef struct ProtocolIE_Container_9515P96 {
	A_SEQUENCE_OF(struct En_gNB_ENDCConfigUpdateAckIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P96_t;
typedef struct ProtocolIE_Container_9515P97 {
	A_SEQUENCE_OF(struct ENDCConfigurationUpdateFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P97_t;
typedef struct ProtocolIE_Container_9515P98 {
	A_SEQUENCE_OF(struct ENDCCellActivationRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P98_t;
typedef struct ProtocolIE_Container_9515P99 {
	A_SEQUENCE_OF(struct ENDCCellActivationResponse_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P99_t;
typedef struct ProtocolIE_Container_9515P100 {
	A_SEQUENCE_OF(struct ENDCCellActivationFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P100_t;
typedef struct ProtocolIE_Container_9515P101 {
	A_SEQUENCE_OF(struct SecondaryRATDataUsageReport_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P101_t;
typedef struct ProtocolIE_Container_9515P102 {
	A_SEQUENCE_OF(struct SgNBActivityNotification_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P102_t;
typedef struct ProtocolIE_Container_9515P103 {
	A_SEQUENCE_OF(struct ENDCPartialResetRequired_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P103_t;
typedef struct ProtocolIE_Container_9515P104 {
	A_SEQUENCE_OF(struct ENDCPartialResetConfirm_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P104_t;
typedef struct ProtocolIE_Container_9515P105 {
	A_SEQUENCE_OF(struct EUTRANRCellResourceCoordinationRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P105_t;
typedef struct ProtocolIE_Container_9515P106 {
	A_SEQUENCE_OF(struct ENB_EUTRA_NRCellResourceCoordinationReqIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P106_t;
typedef struct ProtocolIE_Container_9515P107 {
	A_SEQUENCE_OF(struct En_gNB_EUTRA_NRCellResourceCoordinationReqIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P107_t;
typedef struct ProtocolIE_Container_9515P108 {
	A_SEQUENCE_OF(struct EUTRANRCellResourceCoordinationResponse_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P108_t;
typedef struct ProtocolIE_Container_9515P109 {
	A_SEQUENCE_OF(struct ENB_EUTRA_NRCellResourceCoordinationReqAckIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P109_t;
typedef struct ProtocolIE_Container_9515P110 {
	A_SEQUENCE_OF(struct En_gNB_EUTRA_NRCellResourceCoordinationReqAckIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P110_t;
typedef struct ProtocolIE_Container_9515P111 {
	A_SEQUENCE_OF(struct ENDCX2RemovalRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P111_t;
typedef struct ProtocolIE_Container_9515P112 {
	A_SEQUENCE_OF(struct ENB_ENDCX2RemovalReqIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P112_t;
typedef struct ProtocolIE_Container_9515P113 {
	A_SEQUENCE_OF(struct En_gNB_ENDCX2RemovalReqIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P113_t;
typedef struct ProtocolIE_Container_9515P114 {
	A_SEQUENCE_OF(struct ENDCX2RemovalResponse_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P114_t;
typedef struct ProtocolIE_Container_9515P115 {
	A_SEQUENCE_OF(struct ENB_ENDCX2RemovalReqAckIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P115_t;
typedef struct ProtocolIE_Container_9515P116 {
	A_SEQUENCE_OF(struct En_gNB_ENDCX2RemovalReqAckIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P116_t;
typedef struct ProtocolIE_Container_9515P117 {
	A_SEQUENCE_OF(struct ENDCX2RemovalFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P117_t;
typedef struct ProtocolIE_Container_9515P118 {
	A_SEQUENCE_OF(struct DataForwardingAddressIndication_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P118_t;
typedef struct ProtocolIE_Container_9515P119 {
	A_SEQUENCE_OF(struct GNBStatusIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_9515P119_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P0;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P0_specs_1;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P0_1[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P0_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P1;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P1_specs_3;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P1_3[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P1_constr_3;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P2;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P2_specs_5;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P2_5[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P2_constr_5;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P3;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P3_specs_7;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P3_7[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P3_constr_7;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P4;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P4_specs_9;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P4_9[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P4_constr_9;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P5;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P5_specs_11;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P5_11[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P5_constr_11;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P6;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P6_specs_13;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P6_13[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P6_constr_13;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P7;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P7_specs_15;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P7_15[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P7_constr_15;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P8;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P8_specs_17;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P8_17[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P8_constr_17;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P9;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P9_specs_19;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P9_19[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P9_constr_19;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P10;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P10_specs_21;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P10_21[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P10_constr_21;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P11;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P11_specs_23;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P11_23[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P11_constr_23;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P12;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P12_specs_25;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P12_25[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P12_constr_25;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P13;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P13_specs_27;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P13_27[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P13_constr_27;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P14;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P14_specs_29;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P14_29[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P14_constr_29;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P15;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P15_specs_31;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P15_31[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P15_constr_31;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P16;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P16_specs_33;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P16_33[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P16_constr_33;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P17;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P17_specs_35;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P17_35[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P17_constr_35;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P18;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P18_specs_37;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P18_37[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P18_constr_37;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P19;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P19_specs_39;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P19_39[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P19_constr_39;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P20;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P20_specs_41;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P20_41[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P20_constr_41;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P21;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P21_specs_43;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P21_43[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P21_constr_43;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P22;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P22_specs_45;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P22_45[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P22_constr_45;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P23;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P23_specs_47;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P23_47[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P23_constr_47;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P24;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P24_specs_49;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P24_49[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P24_constr_49;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P25;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P25_specs_51;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P25_51[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P25_constr_51;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P26;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P26_specs_53;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P26_53[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P26_constr_53;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P27;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P27_specs_55;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P27_55[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P27_constr_55;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P28;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P28_specs_57;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P28_57[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P28_constr_57;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P29;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P29_specs_59;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P29_59[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P29_constr_59;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P30;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P30_specs_61;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P30_61[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P30_constr_61;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P31;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P31_specs_63;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P31_63[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P31_constr_63;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P32;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P32_specs_65;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P32_65[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P32_constr_65;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P33;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P33_specs_67;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P33_67[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P33_constr_67;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P34;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P34_specs_69;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P34_69[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P34_constr_69;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P35;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P35_specs_71;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P35_71[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P35_constr_71;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P36;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P36_specs_73;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P36_73[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P36_constr_73;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P37;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P37_specs_75;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P37_75[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P37_constr_75;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P38;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P38_specs_77;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P38_77[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P38_constr_77;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P39;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P39_specs_79;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P39_79[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P39_constr_79;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P40;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P40_specs_81;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P40_81[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P40_constr_81;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P41;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P41_specs_83;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P41_83[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P41_constr_83;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P42;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P42_specs_85;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P42_85[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P42_constr_85;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P43;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P43_specs_87;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P43_87[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P43_constr_87;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P44;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P44_specs_89;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P44_89[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P44_constr_89;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P45;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P45_specs_91;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P45_91[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P45_constr_91;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P46;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P46_specs_93;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P46_93[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P46_constr_93;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P47;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P47_specs_95;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P47_95[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P47_constr_95;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P48;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P48_specs_97;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P48_97[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P48_constr_97;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P49;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P49_specs_99;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P49_99[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P49_constr_99;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P50;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P50_specs_101;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P50_101[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P50_constr_101;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P51;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P51_specs_103;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P51_103[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P51_constr_103;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P52;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P52_specs_105;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P52_105[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P52_constr_105;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P53;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P53_specs_107;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P53_107[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P53_constr_107;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P54;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P54_specs_109;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P54_109[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P54_constr_109;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P55;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P55_specs_111;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P55_111[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P55_constr_111;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P56;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P56_specs_113;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P56_113[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P56_constr_113;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P57;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P57_specs_115;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P57_115[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P57_constr_115;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P58;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P58_specs_117;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P58_117[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P58_constr_117;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P59;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P59_specs_119;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P59_119[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P59_constr_119;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P60;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P60_specs_121;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P60_121[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P60_constr_121;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P61;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P61_specs_123;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P61_123[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P61_constr_123;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P62;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P62_specs_125;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P62_125[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P62_constr_125;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P63;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P63_specs_127;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P63_127[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P63_constr_127;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P64;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P64_specs_129;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P64_129[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P64_constr_129;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P65;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P65_specs_131;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P65_131[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P65_constr_131;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P66;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P66_specs_133;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P66_133[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P66_constr_133;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P67;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P67_specs_135;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P67_135[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P67_constr_135;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P68;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P68_specs_137;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P68_137[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P68_constr_137;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P69;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P69_specs_139;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P69_139[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P69_constr_139;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P70;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P70_specs_141;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P70_141[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P70_constr_141;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P71;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P71_specs_143;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P71_143[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P71_constr_143;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P72;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P72_specs_145;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P72_145[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P72_constr_145;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P73;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P73_specs_147;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P73_147[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P73_constr_147;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P74;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P74_specs_149;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P74_149[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P74_constr_149;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P75;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P75_specs_151;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P75_151[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P75_constr_151;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P76;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P76_specs_153;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P76_153[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P76_constr_153;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P77;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P77_specs_155;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P77_155[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P77_constr_155;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P78;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P78_specs_157;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P78_157[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P78_constr_157;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P79;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P79_specs_159;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P79_159[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P79_constr_159;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P80;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P80_specs_161;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P80_161[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P80_constr_161;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P81;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P81_specs_163;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P81_163[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P81_constr_163;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P82;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P82_specs_165;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P82_165[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P82_constr_165;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P83;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P83_specs_167;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P83_167[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P83_constr_167;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P84;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P84_specs_169;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P84_169[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P84_constr_169;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P85;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P85_specs_171;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P85_171[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P85_constr_171;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P86;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P86_specs_173;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P86_173[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P86_constr_173;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P87;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P87_specs_175;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P87_175[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P87_constr_175;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P88;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P88_specs_177;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P88_177[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P88_constr_177;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P89;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P89_specs_179;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P89_179[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P89_constr_179;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P90;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P90_specs_181;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P90_181[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P90_constr_181;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P91;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P91_specs_183;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P91_183[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P91_constr_183;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P92;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P92_specs_185;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P92_185[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P92_constr_185;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P93;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P93_specs_187;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P93_187[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P93_constr_187;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P94;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P94_specs_189;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P94_189[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P94_constr_189;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P95;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P95_specs_191;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P95_191[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P95_constr_191;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P96;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P96_specs_193;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P96_193[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P96_constr_193;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P97;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P97_specs_195;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P97_195[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P97_constr_195;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P98;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P98_specs_197;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P98_197[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P98_constr_197;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P99;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P99_specs_199;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P99_199[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P99_constr_199;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P100;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P100_specs_201;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P100_201[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P100_constr_201;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P101;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P101_specs_203;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P101_203[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P101_constr_203;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P102;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P102_specs_205;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P102_205[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P102_constr_205;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P103;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P103_specs_207;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P103_207[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P103_constr_207;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P104;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P104_specs_209;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P104_209[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P104_constr_209;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P105;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P105_specs_211;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P105_211[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P105_constr_211;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P106;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P106_specs_213;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P106_213[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P106_constr_213;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P107;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P107_specs_215;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P107_215[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P107_constr_215;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P108;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P108_specs_217;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P108_217[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P108_constr_217;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P109;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P109_specs_219;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P109_219[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P109_constr_219;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P110;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P110_specs_221;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P110_221[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P110_constr_221;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P111;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P111_specs_223;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P111_223[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P111_constr_223;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P112;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P112_specs_225;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P112_225[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P112_constr_225;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P113;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P113_specs_227;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P113_227[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P113_constr_227;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P114;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P114_specs_229;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P114_229[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P114_constr_229;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P115;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P115_specs_231;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P115_231[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P115_constr_231;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P116;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P116_specs_233;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P116_233[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P116_constr_233;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P117;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P117_specs_235;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P117_235[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P117_constr_235;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P118;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P118_specs_237;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P118_237[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P118_constr_237;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_9515P119;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_9515P119_specs_239;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_9515P119_239[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_9515P119_constr_239;

#ifdef __cplusplus
}
#endif

#endif	/* _ProtocolIE_Container_H_ */
#include <asn_internal.h>
