/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-IEs"
 * 	found in "Spec/e2ap-v031ex.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_ProtectedResourceList_H_
#define	_ProtectedResourceList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtectedResourceList_Item;

/* ProtectedResourceList */
typedef struct ProtectedResourceList {
	A_SEQUENCE_OF(struct ProtectedResourceList_Item) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtectedResourceList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProtectedResourceList;
extern asn_SET_OF_specifics_t asn_SPC_ProtectedResourceList_specs_1;
extern asn_TYPE_member_t asn_MBR_ProtectedResourceList_1[1];
extern asn_per_constraints_t asn_PER_type_ProtectedResourceList_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ProtectedResourceList_H_ */
#include <asn_internal.h>
