/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-IEs"
 * 	found in "Spec/e2ap-v031ex.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_RadioframeAllocationOffset_H_
#define	_RadioframeAllocationOffset_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RadioframeAllocationOffset */
typedef long	 RadioframeAllocationOffset_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_RadioframeAllocationOffset_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_RadioframeAllocationOffset;
asn_struct_free_f RadioframeAllocationOffset_free;
asn_struct_print_f RadioframeAllocationOffset_print;
asn_constr_check_f RadioframeAllocationOffset_constraint;
ber_type_decoder_f RadioframeAllocationOffset_decode_ber;
der_type_encoder_f RadioframeAllocationOffset_encode_der;
xer_type_decoder_f RadioframeAllocationOffset_decode_xer;
xer_type_encoder_f RadioframeAllocationOffset_encode_xer;
oer_type_decoder_f RadioframeAllocationOffset_decode_oer;
oer_type_encoder_f RadioframeAllocationOffset_encode_oer;
per_type_decoder_f RadioframeAllocationOffset_decode_uper;
per_type_encoder_f RadioframeAllocationOffset_encode_uper;
per_type_decoder_f RadioframeAllocationOffset_decode_aper;
per_type_encoder_f RadioframeAllocationOffset_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _RadioframeAllocationOffset_H_ */
#include <asn_internal.h>
