/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-PDU-Contents"
 * 	found in "X2AP-15-4-0.asn1"
 * 	`asn1c -D ./asn1_n1 -pdu=auto -fno-include-deps -fcompound-names -findirect-choice -gen-PER -gen-OER -no-gen-example`
 */

#ifndef	_ResponseInformationSgNBReconfComp_H_
#define	_ResponseInformationSgNBReconfComp_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ResponseInformationSgNBReconfComp_PR {
	ResponseInformationSgNBReconfComp_PR_NOTHING,	/* No components present */
	ResponseInformationSgNBReconfComp_PR_success_SgNBReconfComp,
	ResponseInformationSgNBReconfComp_PR_reject_by_MeNB_SgNBReconfComp
	/* Extensions may appear below */
	
} ResponseInformationSgNBReconfComp_PR;

/* Forward declarations */
struct ResponseInformationSgNBReconfComp_SuccessItem;
struct ResponseInformationSgNBReconfComp_RejectByMeNBItem;

/* ResponseInformationSgNBReconfComp */
typedef struct ResponseInformationSgNBReconfComp {
	ResponseInformationSgNBReconfComp_PR present;
	union ResponseInformationSgNBReconfComp_u {
		struct ResponseInformationSgNBReconfComp_SuccessItem	*success_SgNBReconfComp;
		struct ResponseInformationSgNBReconfComp_RejectByMeNBItem	*reject_by_MeNB_SgNBReconfComp;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ResponseInformationSgNBReconfComp_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ResponseInformationSgNBReconfComp;

#ifdef __cplusplus
}
#endif

#endif	/* _ResponseInformationSgNBReconfComp_H_ */
#include <asn_internal.h>
