/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-PDU-Contents"
 * 	found in "X2AP-15-4-0.asn1"
 * 	`asn1c -D ./asn1_n1 -pdu=auto -fno-include-deps -fcompound-names -findirect-choice -gen-PER -gen-OER -no-gen-example`
 */

#ifndef	_ResponseInformationSgNBReconfComp_SuccessItem_H_
#define	_ResponseInformationSgNBReconfComp_SuccessItem_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MeNBtoSgNBContainer.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* ResponseInformationSgNBReconfComp-SuccessItem */
typedef struct ResponseInformationSgNBReconfComp_SuccessItem {
	MeNBtoSgNBContainer_t	*meNBtoSgNBContainer;	/* OPTIONAL */
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ResponseInformationSgNBReconfComp_SuccessItem_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ResponseInformationSgNBReconfComp_SuccessItem;
extern asn_SEQUENCE_specifics_t asn_SPC_ResponseInformationSgNBReconfComp_SuccessItem_specs_1;
extern asn_TYPE_member_t asn_MBR_ResponseInformationSgNBReconfComp_SuccessItem_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ResponseInformationSgNBReconfComp_SuccessItem_H_ */
#include <asn_internal.h>
