/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-IEs"
 * 	found in "Spec/e2ap-v031ex.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_ResumeID_H_
#define	_ResumeID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ResumeID_PR {
	ResumeID_PR_NOTHING,	/* No components present */
	ResumeID_PR_non_truncated,
	ResumeID_PR_truncated
	/* Extensions may appear below */
	
} ResumeID_PR;

/* ResumeID */
typedef struct ResumeID {
	ResumeID_PR present;
	union ResumeID_u {
		BIT_STRING_t	 non_truncated;
		BIT_STRING_t	 truncated;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ResumeID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ResumeID;

#ifdef __cplusplus
}
#endif

#endif	/* _ResumeID_H_ */
#include <asn_internal.h>
