/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-IEs"
 * 	found in "Spec/e2ap-v031ex.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_RICrequestID_H_
#define	_RICrequestID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RICrequestID */
typedef struct RICrequestID {
	long	 ricRequestorID;
	long	 ricRequestSequenceNumber;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RICrequestID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RICrequestID;

#ifdef __cplusplus
}
#endif

#endif	/* _RICrequestID_H_ */
#include <asn_internal.h>
