/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-IEs"
 * 	found in "X2AP-15-4-0.asn1"
 * 	`asn1c -D ./asn1_n1 -pdu=auto -fno-include-deps -fcompound-names -findirect-choice -gen-PER -gen-OER -no-gen-example`
 */

#ifndef	_SecondaryRATUsageReport_Item_H_
#define	_SecondaryRATUsageReport_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "E-RAB-ID.h"
#include <NativeEnumerated.h>
#include "E-RABUsageReportList.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SecondaryRATUsageReport_Item__secondaryRATType {
	SecondaryRATUsageReport_Item__secondaryRATType_nr	= 0
	/*
	 * Enumeration is extensible
	 */
} e_SecondaryRATUsageReport_Item__secondaryRATType;

/* Forward declarations */
struct ProtocolExtensionContainer;

/* SecondaryRATUsageReport-Item */
typedef struct SecondaryRATUsageReport_Item {
	E_RAB_ID_t	 e_RAB_ID;
	long	 secondaryRATType;
	E_RABUsageReportList_t	 e_RABUsageReportList;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SecondaryRATUsageReport_Item_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_secondaryRATType_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SecondaryRATUsageReport_Item;

#ifdef __cplusplus
}
#endif

#endif	/* _SecondaryRATUsageReport_Item_H_ */
#include <asn_internal.h>
