/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-PDU-Contents"
 * 	found in "Spec/e2ap-v031ex.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_ServedCellsToModify_Item_H_
#define	_ServedCellsToModify_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ECGI.h"
#include "ServedCell-Information.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Neighbour_Information;
struct ProtocolExtensionContainer;

/* ServedCellsToModify-Item */
typedef struct ServedCellsToModify_Item {
	ECGI_t	 old_ecgi;
	ServedCell_Information_t	 servedCellInfo;
	struct Neighbour_Information	*neighbour_Info;	/* OPTIONAL */
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ServedCellsToModify_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ServedCellsToModify_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_ServedCellsToModify_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_ServedCellsToModify_Item_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _ServedCellsToModify_Item_H_ */
#include <asn_internal.h>
