/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-PDU-Contents"
 * 	found in "Spec/e2ap-v031ex.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_SgNBReleaseRequest_H_
#define	_SgNBReleaseRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ProtocolIE-Container.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SgNBReleaseRequest */
typedef struct SgNBReleaseRequest {
	ProtocolIE_Container_9515P74_t	 protocolIEs;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SgNBReleaseRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SgNBReleaseRequest;
extern asn_SEQUENCE_specifics_t asn_SPC_SgNBReleaseRequest_specs_1;
extern asn_TYPE_member_t asn_MBR_SgNBReleaseRequest_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _SgNBReleaseRequest_H_ */
#include <asn_internal.h>
