/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-IEs"
 * 	found in "X2AP-15-4-0.asn1"
 * 	`asn1c -D ./asn1_n1 -pdu=auto -fno-include-deps -fcompound-names -findirect-choice -gen-PER -gen-OER -no-gen-example`
 */

#ifndef	_SharedResourceType_H_
#define	_SharedResourceType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SharedResourceType_PR {
	SharedResourceType_PR_NOTHING,	/* No components present */
	SharedResourceType_PR_uLOnlySharing,
	SharedResourceType_PR_uLandDLSharing
	/* Extensions may appear below */
	
} SharedResourceType_PR;

/* Forward declarations */
struct ULOnlySharing;
struct ULandDLSharing;

/* SharedResourceType */
typedef struct SharedResourceType {
	SharedResourceType_PR present;
	union SharedResourceType_u {
		struct ULOnlySharing	*uLOnlySharing;
		struct ULandDLSharing	*uLandDLSharing;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SharedResourceType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SharedResourceType;
extern asn_CHOICE_specifics_t asn_SPC_SharedResourceType_specs_1;
extern asn_TYPE_member_t asn_MBR_SharedResourceType_1[2];
extern asn_per_constraints_t asn_PER_type_SharedResourceType_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _SharedResourceType_H_ */
#include <asn_internal.h>
