/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-IEs"
 * 	found in "X2AP-15-4-0.asn1"
 * 	`asn1c -D ./asn1_n1 -pdu=auto -fno-include-deps -fcompound-names -findirect-choice -gen-PER -gen-OER -no-gen-example`
 */

#ifndef	_SplitSRBs_H_
#define	_SplitSRBs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SplitSRBs {
	SplitSRBs_srb1	= 0,
	SplitSRBs_srb2	= 1,
	SplitSRBs_srb1and2	= 2
	/*
	 * Enumeration is extensible
	 */
} e_SplitSRBs;

/* SplitSRBs */
typedef long	 SplitSRBs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SplitSRBs;
asn_struct_free_f SplitSRBs_free;
asn_struct_print_f SplitSRBs_print;
asn_constr_check_f SplitSRBs_constraint;
ber_type_decoder_f SplitSRBs_decode_ber;
der_type_encoder_f SplitSRBs_encode_der;
xer_type_decoder_f SplitSRBs_decode_xer;
xer_type_encoder_f SplitSRBs_encode_xer;
oer_type_decoder_f SplitSRBs_decode_oer;
oer_type_encoder_f SplitSRBs_encode_oer;
per_type_decoder_f SplitSRBs_decode_uper;
per_type_encoder_f SplitSRBs_encode_uper;
per_type_decoder_f SplitSRBs_decode_aper;
per_type_encoder_f SplitSRBs_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SplitSRBs_H_ */
#include <asn_internal.h>
