/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-IEs"
 * 	found in "X2AP-15-4-0.asn1"
 * 	`asn1c -D ./asn1_n1 -pdu=auto -fno-include-deps -fcompound-names -findirect-choice -gen-PER -gen-OER -no-gen-example`
 */

#ifndef	_SplitSRB_H_
#define	_SplitSRB_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RRCContainer.h"
#include "SRBType.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DeliveryStatus;
struct ProtocolExtensionContainer;

/* SplitSRB */
typedef struct SplitSRB {
	RRCContainer_t	*rrcContainer;	/* OPTIONAL */
	SRBType_t	 srbType;
	struct DeliveryStatus	*deliveryStatus;	/* OPTIONAL */
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SplitSRB_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SplitSRB;

#ifdef __cplusplus
}
#endif

#endif	/* _SplitSRB_H_ */
#include <asn_internal.h>
