/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-IEs"
 * 	found in "Spec/e2ap-v031ex.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_TAI_Item_H_
#define	_TAI_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TAC.h"
#include "PLMN-Identity.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* TAI-Item */
typedef struct TAI_Item {
	TAC_t	 tAC;
	PLMN_Identity_t	 pLMN_Identity;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TAI_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TAI_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_TAI_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_TAI_Item_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _TAI_Item_H_ */
#include <asn_internal.h>
