/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-IEs"
 * 	found in "X2AP-15-4-0.asn1"
 * 	`asn1c -D ./asn1_n1 -pdu=auto -fno-include-deps -fcompound-names -findirect-choice -gen-PER -gen-OER -no-gen-example`
 */

#ifndef	_TAIListforQMC_H_
#define	_TAIListforQMC_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TAI_Item;

/* TAIListforQMC */
typedef struct TAIListforQMC {
	A_SEQUENCE_OF(struct TAI_Item) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TAIListforQMC_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TAIListforQMC;
extern asn_SET_OF_specifics_t asn_SPC_TAIListforQMC_specs_1;
extern asn_TYPE_member_t asn_MBR_TAIListforQMC_1[1];
extern asn_per_constraints_t asn_PER_type_TAIListforQMC_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _TAIListforQMC_H_ */
#include <asn_internal.h>
