/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-gNB-X2-IEs"
 * 	found in "Spec/e2ap-v031ex.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_TypeOfMessage_H_
#define	_TypeOfMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TypeOfMessage {
	TypeOfMessage_nothing	= 0,
	TypeOfMessage_initiating_message	= 1,
	TypeOfMessage_successful_outcome	= 2,
	TypeOfMessage_unsuccessful_outcome	= 3
} e_TypeOfMessage;

/* TypeOfMessage */
typedef long	 TypeOfMessage_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TypeOfMessage_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TypeOfMessage;
extern const asn_INTEGER_specifics_t asn_SPC_TypeOfMessage_specs_1;
asn_struct_free_f TypeOfMessage_free;
asn_struct_print_f TypeOfMessage_print;
asn_constr_check_f TypeOfMessage_constraint;
ber_type_decoder_f TypeOfMessage_decode_ber;
der_type_encoder_f TypeOfMessage_encode_der;
xer_type_decoder_f TypeOfMessage_decode_xer;
xer_type_encoder_f TypeOfMessage_encode_xer;
oer_type_decoder_f TypeOfMessage_decode_oer;
oer_type_encoder_f TypeOfMessage_encode_oer;
per_type_decoder_f TypeOfMessage_decode_uper;
per_type_encoder_f TypeOfMessage_encode_uper;
per_type_decoder_f TypeOfMessage_decode_aper;
per_type_encoder_f TypeOfMessage_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _TypeOfMessage_H_ */
#include <asn_internal.h>
