/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-PDU-Contents"
 * 	found in "X2AP-15-4-0.asn1"
 * 	`asn1c -D ./asn1_n1 -pdu=auto -fno-include-deps -fcompound-names -findirect-choice -gen-PER -gen-OER -no-gen-example`
 */

#ifndef	_UE_ContextInformationSeNBModReq_H_
#define	_UE_ContextInformationSeNBModReq_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SeNBSecurityKey.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct UESecurityCapabilities;
struct UEAggregateMaximumBitRate;
struct E_RABs_ToBeAdded_List_ModReq;
struct E_RABs_ToBeModified_List_ModReq;
struct E_RABs_ToBeReleased_List_ModReq;
struct ProtocolExtensionContainer;

/* UE-ContextInformationSeNBModReq */
typedef struct UE_ContextInformationSeNBModReq {
	struct UESecurityCapabilities	*uE_SecurityCapabilities;	/* OPTIONAL */
	SeNBSecurityKey_t	*seNB_SecurityKey;	/* OPTIONAL */
	struct UEAggregateMaximumBitRate	*seNBUEAggregateMaximumBitRate;	/* OPTIONAL */
	struct E_RABs_ToBeAdded_List_ModReq	*e_RABs_ToBeAdded;	/* OPTIONAL */
	struct E_RABs_ToBeModified_List_ModReq	*e_RABs_ToBeModified;	/* OPTIONAL */
	struct E_RABs_ToBeReleased_List_ModReq	*e_RABs_ToBeReleased;	/* OPTIONAL */
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UE_ContextInformationSeNBModReq_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UE_ContextInformationSeNBModReq;

#ifdef __cplusplus
}
#endif

#endif	/* _UE_ContextInformationSeNBModReq_H_ */
#include <asn_internal.h>
