/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-PDU-Contents"
 * 	found in "Spec/e2ap-v031ex.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_UE_ContextReferenceAtSgNB_H_
#define	_UE_ContextReferenceAtSgNB_H_


#include <asn_application.h>

/* Including external dependencies */
#include "GlobalGNB-ID.h"
#include "SgNB-UE-X2AP-ID.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* UE-ContextReferenceAtSgNB */
typedef struct UE_ContextReferenceAtSgNB {
	GlobalGNB_ID_t	 source_GlobalSgNB_ID;
	SgNB_UE_X2AP_ID_t	 sgNB_UE_X2AP_ID;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UE_ContextReferenceAtSgNB_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UE_ContextReferenceAtSgNB;

#ifdef __cplusplus
}
#endif

#endif	/* _UE_ContextReferenceAtSgNB_H_ */
#include <asn_internal.h>
