/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-PDU-Contents"
 * 	found in "Spec/e2ap-v031ex.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_UE_ContextReferenceAtWT_H_
#define	_UE_ContextReferenceAtWT_H_


#include <asn_application.h>

/* Including external dependencies */
#include "WTID.h"
#include "WT-UE-XwAP-ID.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* UE-ContextReferenceAtWT */
typedef struct UE_ContextReferenceAtWT {
	WTID_t	 wTID;
	WT_UE_XwAP_ID_t	 wT_UE_XwAP_ID;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UE_ContextReferenceAtWT_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UE_ContextReferenceAtWT;

#ifdef __cplusplus
}
#endif

#endif	/* _UE_ContextReferenceAtWT_H_ */
#include <asn_internal.h>
