/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-IEs"
 * 	found in "X2AP-15-4-0.asn1"
 * 	`asn1c -D ./asn1_n1 -pdu=auto -fno-include-deps -fcompound-names -findirect-choice -gen-PER -gen-OER -no-gen-example`
 */

#ifndef	_UE_ContextKeptIndicator_H_
#define	_UE_ContextKeptIndicator_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UE_ContextKeptIndicator {
	UE_ContextKeptIndicator_true	= 0
	/*
	 * Enumeration is extensible
	 */
} e_UE_ContextKeptIndicator;

/* UE-ContextKeptIndicator */
typedef long	 UE_ContextKeptIndicator_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UE_ContextKeptIndicator;
asn_struct_free_f UE_ContextKeptIndicator_free;
asn_struct_print_f UE_ContextKeptIndicator_print;
asn_constr_check_f UE_ContextKeptIndicator_constraint;
ber_type_decoder_f UE_ContextKeptIndicator_decode_ber;
der_type_encoder_f UE_ContextKeptIndicator_encode_der;
xer_type_decoder_f UE_ContextKeptIndicator_decode_xer;
xer_type_encoder_f UE_ContextKeptIndicator_encode_xer;
oer_type_decoder_f UE_ContextKeptIndicator_decode_oer;
oer_type_encoder_f UE_ContextKeptIndicator_encode_oer;
per_type_decoder_f UE_ContextKeptIndicator_decode_uper;
per_type_encoder_f UE_ContextKeptIndicator_encode_uper;
per_type_decoder_f UE_ContextKeptIndicator_decode_aper;
per_type_encoder_f UE_ContextKeptIndicator_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _UE_ContextKeptIndicator_H_ */
#include <asn_internal.h>
