/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-IEs"
 * 	found in "Spec/e2ap-v031ex.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_UL_HighInterferenceIndication_H_
#define	_UL_HighInterferenceIndication_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UL-HighInterferenceIndication */
typedef BIT_STRING_t	 UL_HighInterferenceIndication_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_UL_HighInterferenceIndication_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_UL_HighInterferenceIndication;
asn_struct_free_f UL_HighInterferenceIndication_free;
asn_struct_print_f UL_HighInterferenceIndication_print;
asn_constr_check_f UL_HighInterferenceIndication_constraint;
ber_type_decoder_f UL_HighInterferenceIndication_decode_ber;
der_type_encoder_f UL_HighInterferenceIndication_encode_der;
xer_type_decoder_f UL_HighInterferenceIndication_decode_xer;
xer_type_encoder_f UL_HighInterferenceIndication_encode_xer;
oer_type_decoder_f UL_HighInterferenceIndication_decode_oer;
oer_type_encoder_f UL_HighInterferenceIndication_encode_oer;
per_type_decoder_f UL_HighInterferenceIndication_decode_uper;
per_type_encoder_f UL_HighInterferenceIndication_encode_uper;
per_type_decoder_f UL_HighInterferenceIndication_decode_aper;
per_type_encoder_f UL_HighInterferenceIndication_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _UL_HighInterferenceIndication_H_ */
#include <asn_internal.h>
