/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-IEs"
 * 	found in "Spec/e2ap-v031ex.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_UL_InterferenceOverloadIndication_Item_H_
#define	_UL_InterferenceOverloadIndication_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UL_InterferenceOverloadIndication_Item {
	UL_InterferenceOverloadIndication_Item_high_interference	= 0,
	UL_InterferenceOverloadIndication_Item_medium_interference	= 1,
	UL_InterferenceOverloadIndication_Item_low_interference	= 2
	/*
	 * Enumeration is extensible
	 */
} e_UL_InterferenceOverloadIndication_Item;

/* UL-InterferenceOverloadIndication-Item */
typedef long	 UL_InterferenceOverloadIndication_Item_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_UL_InterferenceOverloadIndication_Item_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_UL_InterferenceOverloadIndication_Item;
extern const asn_INTEGER_specifics_t asn_SPC_UL_InterferenceOverloadIndication_Item_specs_1;
asn_struct_free_f UL_InterferenceOverloadIndication_Item_free;
asn_struct_print_f UL_InterferenceOverloadIndication_Item_print;
asn_constr_check_f UL_InterferenceOverloadIndication_Item_constraint;
ber_type_decoder_f UL_InterferenceOverloadIndication_Item_decode_ber;
der_type_encoder_f UL_InterferenceOverloadIndication_Item_encode_der;
xer_type_decoder_f UL_InterferenceOverloadIndication_Item_decode_xer;
xer_type_encoder_f UL_InterferenceOverloadIndication_Item_encode_xer;
oer_type_decoder_f UL_InterferenceOverloadIndication_Item_decode_oer;
oer_type_encoder_f UL_InterferenceOverloadIndication_Item_encode_oer;
per_type_decoder_f UL_InterferenceOverloadIndication_Item_decode_uper;
per_type_encoder_f UL_InterferenceOverloadIndication_Item_encode_uper;
per_type_decoder_f UL_InterferenceOverloadIndication_Item_decode_aper;
per_type_encoder_f UL_InterferenceOverloadIndication_Item_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _UL_InterferenceOverloadIndication_Item_H_ */
#include <asn_internal.h>
