/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-PDU-Descriptions"
 * 	found in "Spec/e2ap-v031ex.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_UnsuccessfulOutcomeE2_H_
#define	_UnsuccessfulOutcomeE2_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ProcedureCode.h"
#include "Criticality.h"
#include <ANY.h>
#include <asn_ioc.h>
#include "RICsubscriptionRequest.h"
#include "RICsubscriptionResponse.h"
#include "RICsubscriptionFailure.h"
#include "RICsubscriptionDeleteRequest.h"
#include "RICsubscriptionDeleteResponse.h"
#include "RICsubscriptionDeleteFailure.h"
#include "RICserviceUpdate.h"
#include "RICserviceUpdateAcknowledge.h"
#include "RICserviceUpdateFailure.h"
#include "RICcontrolRequest.h"
#include "RICcontrolAcknowledge.h"
#include "RICcontrolFailure.h"
#include "RICindication.h"
#include "RICserviceQuery.h"
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UnsuccessfulOutcomeE2__value_PR {
	UnsuccessfulOutcomeE2__value_PR_NOTHING,	/* No components present */
	UnsuccessfulOutcomeE2__value_PR_RICsubscriptionFailure,
	UnsuccessfulOutcomeE2__value_PR_RICsubscriptionDeleteFailure,
	UnsuccessfulOutcomeE2__value_PR_RICserviceUpdateFailure,
	UnsuccessfulOutcomeE2__value_PR_RICcontrolFailure
} UnsuccessfulOutcomeE2__value_PR;

/* UnsuccessfulOutcomeE2 */
typedef struct UnsuccessfulOutcomeE2 {
	ProcedureCode_t	 procedureCode;
	Criticality_t	 criticality;
	struct UnsuccessfulOutcomeE2__value {
		UnsuccessfulOutcomeE2__value_PR present;
		union UnsuccessfulOutcomeE2__value_u {
			RICsubscriptionFailure_t	 RICsubscriptionFailure;
			RICsubscriptionDeleteFailure_t	 RICsubscriptionDeleteFailure;
			RICserviceUpdateFailure_t	 RICserviceUpdateFailure;
			RICcontrolFailure_t	 RICcontrolFailure;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UnsuccessfulOutcomeE2_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UnsuccessfulOutcomeE2;
extern asn_SEQUENCE_specifics_t asn_SPC_UnsuccessfulOutcomeE2_specs_1;
extern asn_TYPE_member_t asn_MBR_UnsuccessfulOutcomeE2_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _UnsuccessfulOutcomeE2_H_ */
#include <asn_internal.h>
