/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-IEs"
 * 	found in "X2AP-15-4-0.asn1"
 * 	`asn1c -D ./asn1_n1 -pdu=auto -fno-include-deps -fcompound-names -findirect-choice -gen-PER -gen-OER -no-gen-example`
 */

#ifndef	_WidebandCQICodeword1_H_
#define	_WidebandCQICodeword1_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum WidebandCQICodeword1_PR {
	WidebandCQICodeword1_PR_NOTHING,	/* No components present */
	WidebandCQICodeword1_PR_four_bitCQI,
	WidebandCQICodeword1_PR_three_bitSpatialDifferentialCQI
	/* Extensions may appear below */
	
} WidebandCQICodeword1_PR;

/* WidebandCQICodeword1 */
typedef struct WidebandCQICodeword1 {
	WidebandCQICodeword1_PR present;
	union WidebandCQICodeword1_u {
		long	 four_bitCQI;
		long	 three_bitSpatialDifferentialCQI;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} WidebandCQICodeword1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_WidebandCQICodeword1;
extern asn_CHOICE_specifics_t asn_SPC_WidebandCQICodeword1_specs_1;
extern asn_TYPE_member_t asn_MBR_WidebandCQICodeword1_1[2];
extern asn_per_constraints_t asn_PER_type_WidebandCQICodeword1_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _WidebandCQICodeword1_H_ */
#include <asn_internal.h>
