/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-PDU-Contents"
 * 	found in "Spec/e2ap-v031ex.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_X2AP_Message_H_
#define	_X2AP_Message_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* X2AP-Message */
typedef OCTET_STRING_t	 X2AP_Message_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_X2AP_Message;
asn_struct_free_f X2AP_Message_free;
asn_struct_print_f X2AP_Message_print;
asn_constr_check_f X2AP_Message_constraint;
ber_type_decoder_f X2AP_Message_decode_ber;
der_type_encoder_f X2AP_Message_encode_der;
xer_type_decoder_f X2AP_Message_decode_xer;
xer_type_encoder_f X2AP_Message_encode_xer;
oer_type_decoder_f X2AP_Message_decode_oer;
oer_type_encoder_f X2AP_Message_encode_oer;
per_type_decoder_f X2AP_Message_decode_uper;
per_type_encoder_f X2AP_Message_encode_uper;
per_type_decoder_f X2AP_Message_decode_aper;
per_type_encoder_f X2AP_Message_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _X2AP_Message_H_ */
#include <asn_internal.h>
