/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-PDU-Descriptions"
 * 	found in "Spec/e2ap-v031ex.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_X2AP_PDU_H_
#define	_X2AP_PDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum X2AP_PDU_PR {
	X2AP_PDU_PR_NOTHING,	/* No components present */
	X2AP_PDU_PR_initiatingMessage,
	X2AP_PDU_PR_successfulOutcome,
	X2AP_PDU_PR_unsuccessfulOutcome
	/* Extensions may appear below */
	
} X2AP_PDU_PR;

/* Forward declarations */
struct InitiatingMessage;
struct SuccessfulOutcome;
struct UnsuccessfulOutcome;

/* X2AP-PDU */
typedef struct X2AP_PDU {
	X2AP_PDU_PR present;
	union X2AP_PDU_u {
		struct InitiatingMessage	*initiatingMessage;
		struct SuccessfulOutcome	*successfulOutcome;
		struct UnsuccessfulOutcome	*unsuccessfulOutcome;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} X2AP_PDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_X2AP_PDU;

#ifdef __cplusplus
}
#endif

#endif	/* _X2AP_PDU_H_ */
#include <asn_internal.h>
