/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-IEs"
 * 	found in "Spec/e2ap-v031ex.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER`
 */

#ifndef	_X2BenefitValue_H_
#define	_X2BenefitValue_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* X2BenefitValue */
typedef long	 X2BenefitValue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_X2BenefitValue;
asn_struct_free_f X2BenefitValue_free;
asn_struct_print_f X2BenefitValue_print;
asn_constr_check_f X2BenefitValue_constraint;
ber_type_decoder_f X2BenefitValue_decode_ber;
der_type_encoder_f X2BenefitValue_encode_der;
xer_type_decoder_f X2BenefitValue_decode_xer;
xer_type_encoder_f X2BenefitValue_encode_xer;
oer_type_decoder_f X2BenefitValue_decode_oer;
oer_type_encoder_f X2BenefitValue_encode_oer;
per_type_decoder_f X2BenefitValue_decode_uper;
per_type_encoder_f X2BenefitValue_encode_uper;
per_type_decoder_f X2BenefitValue_decode_aper;
per_type_encoder_f X2BenefitValue_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _X2BenefitValue_H_ */
#include <asn_internal.h>
