/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_E2AP_PDU;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_gNB_X2_eventTriggerDefinition;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_gNB_X2_actionDefinition;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_gNB_X2_indicationHeader;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_gNB_X2_indicationMessage;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_gNB_X2_callProcessID;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_gNB_X2_controlHeader;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_gNB_X2_controlMessage;
extern struct asn_TYPE_descriptor_s asn_DEF_X2AP_PDU;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module E2AP-PDU-Descriptions in Spec/e2ap-v031ex.asn */
	&asn_DEF_E2AP_PDU,	
	/* From module E2SM-gNB-X2-IEs in Spec/e2ap-v031ex.asn */
	&asn_DEF_E2SM_gNB_X2_eventTriggerDefinition,	
	&asn_DEF_E2SM_gNB_X2_actionDefinition,	
	&asn_DEF_E2SM_gNB_X2_indicationHeader,	
	&asn_DEF_E2SM_gNB_X2_indicationMessage,	
	&asn_DEF_E2SM_gNB_X2_callProcessID,	
	&asn_DEF_E2SM_gNB_X2_controlHeader,	
	&asn_DEF_E2SM_gNB_X2_controlMessage,	
	/* From module X2AP-PDU-Descriptions in Spec/e2ap-v031ex.asn */
	&asn_DEF_X2AP_PDU,	
	0
};

