/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-PDU-Contents"
 * 	found in "X2AP-15-4-0.asn1"
 * 	`asn1c -D ./asn1_n1 -pdu=auto -fno-include-deps -fcompound-names -findirect-choice -gen-PER -gen-OER -no-gen-example`
 */

#include "ResponseInformationSeNBReconfComp-RejectByMeNBItem.h"

#include "ProtocolExtensionContainer.h"
asn_TYPE_member_t asn_MBR_ResponseInformationSeNBReconfComp_RejectByMeNBItem_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ResponseInformationSeNBReconfComp_RejectByMeNBItem, cause),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Cause,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cause"
		},
	{ ATF_POINTER, 2, offsetof(struct ResponseInformationSeNBReconfComp_RejectByMeNBItem, meNBtoSeNBContainer),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeNBtoSeNBContainer,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"meNBtoSeNBContainer"
		},
	{ ATF_POINTER, 1, offsetof(struct ResponseInformationSeNBReconfComp_RejectByMeNBItem, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_7683P22,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_ResponseInformationSeNBReconfComp_RejectByMeNBItem_oms_1[] = { 1, 2 };
static const ber_tlv_tag_t asn_DEF_ResponseInformationSeNBReconfComp_RejectByMeNBItem_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ResponseInformationSeNBReconfComp_RejectByMeNBItem_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* cause */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* meNBtoSeNBContainer */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_ResponseInformationSeNBReconfComp_RejectByMeNBItem_specs_1 = {
	sizeof(struct ResponseInformationSeNBReconfComp_RejectByMeNBItem),
	offsetof(struct ResponseInformationSeNBReconfComp_RejectByMeNBItem, _asn_ctx),
	asn_MAP_ResponseInformationSeNBReconfComp_RejectByMeNBItem_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_ResponseInformationSeNBReconfComp_RejectByMeNBItem_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ResponseInformationSeNBReconfComp_RejectByMeNBItem = {
	"ResponseInformationSeNBReconfComp-RejectByMeNBItem",
	"ResponseInformationSeNBReconfComp-RejectByMeNBItem",
	&asn_OP_SEQUENCE,
	asn_DEF_ResponseInformationSeNBReconfComp_RejectByMeNBItem_tags_1,
	sizeof(asn_DEF_ResponseInformationSeNBReconfComp_RejectByMeNBItem_tags_1)
		/sizeof(asn_DEF_ResponseInformationSeNBReconfComp_RejectByMeNBItem_tags_1[0]), /* 1 */
	asn_DEF_ResponseInformationSeNBReconfComp_RejectByMeNBItem_tags_1,	/* Same as above */
	sizeof(asn_DEF_ResponseInformationSeNBReconfComp_RejectByMeNBItem_tags_1)
		/sizeof(asn_DEF_ResponseInformationSeNBReconfComp_RejectByMeNBItem_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ResponseInformationSeNBReconfComp_RejectByMeNBItem_1,
	3,	/* Elements count */
	&asn_SPC_ResponseInformationSeNBReconfComp_RejectByMeNBItem_specs_1	/* Additional specs */
};

